version: '3.9'
services:
    with-pw:
        image: redis
        restart: always
        ports:
            - 6179:6379
        volumes:
            - redis_data_b:/data
        env_file: .env
        entrypoint: redis-server --appendonly yes  --requirepass ${REDIS_PASSWORD}
    
volumes:
    redis_data_b:

networks:
  default:
    name: redis_network